# Set the server Port
server:
  port: 2020

# Name of the application and server where to fetch the configuration information for this service.
spring:
  application:
    name: phones
  cloud:
    config:
      uri: http://localhost:4040
