# Application name and config server port.
server:
  port: ${PORT:2020}

# This is for health checkof the application.
# http://localhost:1020/health  
#management:
#  port: ${PORT:1009}
  
# Spring - application Name, Cache, JPA and datasource configuration. 
spring:
  application:
    name: phones-service
  jpa: 
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/phonedb
    username: root
    password: root
  cache:
    ehcache:
      config: classpath:ehcache.xml

# logging support.    
logging: 
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN
      
##########################################
#     Eureka Client configuration        #
########################################## 
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
#### End: Eureka Client configuration ####