# This is common configuration between all services.

# Eureka configurtion between all services.
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/    

spring:
  profiles:
      active: test
      
      
#Dev environment

spring:
  jpa: 
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/phonedb
    username: root
    password: root
