#Local environment


# Set profile and JPA HSQL configuration.
spring:
  jpa: 
    database: HSQL
    hibernate:
      ddl-auto: update
  datasource: 
    driverClassName: org.hsqldb.jdbcDriver
    username: sa
    password: 
    url: jdbc:hsqldb:file:database/demo/phoneDB.db