# Set the server Port
#server:
#  port: 8761
  
# Name of the application
spring:
  application:
    name: eureka
  cloud:
    config:
      uri: http://localhost:4040
    
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false



